version: '3'
services:
  postgres:
    image: 'postgres:12'
    environment:
      - 'POSTGRES_DB=sp_task'
      - 'POSTGRES_PASSWORD=sp_task'
      - 'POSTGRES_USER=sp_task'
      - 'PGDATA=/var/lib/postgresql/data/pgdata'
    ports:
      - '24851:5432'
    volumes:
      - postgres-storage:/var/lib/postgresql/data
volumes:
  postgres-storage:
