spring:
  datasource:
    url: jdbc:postgresql://localhost:24851/sp_task
    username: sp_task
    password: sp_task
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
  logging:
    level:
      org:
        hibernate:
          type: trace
